# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version: 3
final_space: true
palette:
  blue: '#1e66f5'
  closer: p:os
  lavender: '#7287FD'
  os: '#ACB0BE'
  pink: '#ea76cb'
upgrade:
  source: cdn
  interval: 168h
  auto: false
  notice: false
blocks:
  - type: prompt
    alignment: left
    segments:
      - template: '{{.Icon}} '
        foreground: p:os
        type: os
        style: plain
      - properties:
          folder_icon: ....
          home_icon: "~"
          style: agnoster_short
        template: '{{ .Path }} '
        foreground: p:pink
        type: path
        style: plain
      - properties:
          branch_icon: ' '
          cherry_pick_icon: ' '
          commit_icon: ' '
          fetch_status: false
          fetch_upstream_icon: false
          merge_icon: ' '
          no_commits_icon: ' '
          rebase_icon: ' '
          revert_icon: ' '
          tag_icon: ' '
        template: '{{ .HEAD }} '
        foreground: p:lavender
        type: git
        style: plain
      - template: 
        foreground_templates:
          - "{{ if gt .Code 0 }}p:closer{{ end }}"
          - "{{ if eq .Code 0 }}p:lavender{{ end }}"
        type: text
        style: plain
